#!/bin/sh
QMAILDUID=`id -u vpopmail`
QMAILDGID=`id -g vpopmail`
HOSTNAME=`cat /var/qmail/control/me`
CONCURRENCY=`cat /var/qmail/control/concurrencyincoming`
export SMTPAUTH=""
export UCSPITLS=""
. /var/qmail/ssl_env
exec env PATH="/var/qmail/bin:$PATH" \
    sslserver \
    -4 -6 \
    -seVn -Rp -l $HOSTNAME -c $CONCURRENCY \
    -Xx /var/qmail/control/rules.smtpd.cdb \
    -u $QMAILDUID -g $QMAILDGID :0 smtp \
    /usr/local/bin/rblsmtpd -W -C -r sbl-xbl.spamhaus.org \
    /var/qmail/bin/qmail-smtpd /var/vpopmail/bin/vchkpw /bin/true 2>&1
